apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nginx-starter
  namespace: test
spec:
  #this is in UTC
  schedule: "46 6 * * *"
  startingDeadlineSeconds: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:      
      template:
        spec:
          serviceAccountName: applicationScaler
          containers:
          - name: applicationScaler
            image: applicationScaler
            command: ["/applicationScaler"]
            args: ["--namespace","test", "--label", "app=nginx", "--action" , "start"]
          restartPolicy: OnFailure
