---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: applicationScaler
  namespace: test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: applicationScaler
  namespace: test
rules:
- apiGroups: ["extensions","apps"]
  resources: ["deployments","statefulsets"]
  verbs: ["get", "list", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: applicationScaler
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: applicationScaler
subjects:
- kind: ServiceAccount
  name: applicationScaler

