{{- range .Values.cronjobs }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .cronjob.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  #this is in UTC
  schedule: {{ .cronjob.schedule }}
  startingDeadlineSeconds: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:      
      template:
        spec:
          serviceAccountName: {{ $.Values.serviceAccountName }}
          containers:
          - name: applicationScaler
            image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            command: ["/applicationScaler"]
            args: ["--namespace","{{ $.Release.Namespace }}", "--label", "{{ .cronjob.label }}", "--action" , "{{ .cronjob.action }}"]
          restartPolicy: OnFailure
---
{{- end }}
